mysite/code_and_crossword/urls.py
from django.conf.urls import url

from . import views

app_name = 'code_and_crossword'
urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^(?P<level>[0-9]+)/code/$', views.code, name='code'),
    url(r'^(?P<level>[0-9]+)/code_check/$', views.code_check, name='code_check'),
    url(r'^(?P<level>[0-9]+)/crossword/$', views.crossword, name='crossword'),
    url(r'^(?P<level>[0-9]+)/crossword_check/$', views.crossword_check, name='crossword_check'),
    url(r'^(?P<level>[0-9]+)/(?P<success_type>[code|crossword]+)/success/$', views.success, name='success'), 
    url(r'^leaderboard', views.leaderboard, name='leaderboard'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^code_and_crossword/', include('code_and_crossword.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/code_and_crossword/models.py
from __future__ import unicode_literals

from django.db import models
from django import forms

# Create your models here.

class Leaderboard(models.Model):
	name = models.CharField(max_length = 20)
	sub_date = models.DateTimeField('submission date')
	score = models.IntegerField()
	code_score = models.IntegerField()
	crossword_score = models.IntegerField()

class Code(models.Model):
	question = models.CharField(max_length = 1000)
	level = models.IntegerField()

	def __str__(self):
		return self.question + ". level = " + str(self.level)

class Code_Answer(forms.Form):
	answer = forms.CharField(max_length = 1000)

class Crossword(models.Model):
	question = models.CharField(max_length = 3000)
	level = models.IntegerField()

	def __str__(self):
		return self.question + ". level = " + str(self.level)

class Crossword_Answer(forms.Form):
	answer = forms.CharField(max_length = 3000)

mysite/code_and_crossword/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
# from .forms import UploadFileForm
# from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.urlresolvers import reverse
from .models import Code, Crossword, Code_Answer, Crossword_Answer

# Create your views here.

'''
POINTS TO CONSIDER:
When and how to increment level.
How to save user data at the end of the level.
'''

def index(request):
	code_questions = Code.objects.all()
	code_count = 0
	if code_questions:
		for question in code_questions:
			code_count += 1
	crossword_questions = Crossword.objects.all()
	crossword_count = 0
	if crossword_questions:
		for question in crossword_questions:
			crossword_count += 1
	context = {'code_questions': code_questions, 'crossword_questions': crossword_questions, 'code_count': code_count, 'crossword_count': crossword_count}
	return render(request, 'code_and_crossword/index.html', context)

def code(request, level):
	try:
		question = Code.objects.get(level=level)
	except Code.DoesNotExist:
		raise Http404("Coding challenge does not exist")

	return render(request, 'code_and_crossword/code.html', {'question': question})
	
def crossword(request, level):
	try:
		question = Crossword.objects.get(level=level)
	except Code.DoesNotExist:
		raise Http404("Crossword puzzle does not exist")

	return render(request, 'code_and_crossword/crossword.html', {'question': question})

def verify_answer(answer):
	if answer == "yes":
		return True
	return False

def code_check(request, level):

	# after getting post data, the form checks if all good and redirects to success page. Else, it renders again with an error

	answer = request.POST['answer']
	if verify_answer(answer) is True:

		# Always return an HttpResponseRedirect after successfully dealing
	    # with POST data. This prevents data from being posted twice if a
	    # user hits the Back button.
	# increment level
		success_type = 'code'
		return HttpResponseRedirect(reverse('code_and_crossword:success', args=(level, success_type)))

	else:
		# answer is invalid
		return render(request, 'code_and_crossword/code.html', { 'question': Code.objects.get(level=level), 'error_message': 'Your answer is invalid.' })

def crossword_check(request, level):

	# after getting post data, the form checks if all good and redirects to success page. Else, it renders again with an error

	answer = request.POST['answer']
	if verify_answer(answer) is True:

		# Always return an HttpResponseRedirect after successfully dealing
	    # with POST data. This prevents data from being posted twice if a
	    # user hits the Back button.
	# increment level
		success_type = 'crossword'
		return HttpResponseRedirect(reverse('code_and_crossword:success', args=(level, success_type)))

	else:
		# answer is invalid
		return render(request, 'code_and_crossword/crossword.html', { 'question': Crossword.objects.get(level=level), 'error_message': 'Your answer is invalid.' })

def success(request, level, success_type):
	if success_type == 'code':
		question = Code.objects.get(level=level)
	elif success_type == 'crossword':
		question = Crossword.objects.get(level=level)
	return render(request, 'code_and_crossword/success.html', {'question': question, 'success_type': success_type})

# def handle_uploaded_file(f):
#     with open('some/file/name.txt', 'rb+') as destination:
#         for chunk in f.chunks():
#             destination.read(chunk)
	
def leaderboard(request):

	return render(request, 'code_and_crossword/leaderboard.html', {})

mysite/code_and_crossword/templates/code_and_crossword/code.html
<h1> You're on the code question in level {{ question.level }}.<br>
Question: {{ question.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- input form for uploading code -->
<form action="{% url 'code_and_crossword:code_check' question.level %}" method="POST">
	{% csrf_token %}
    <input type="text" name="answer" id="submission {{ question.level }}" value="# Use any language."/> <!-- Must define another check for language type here later" /> -->
     <!-- <label for="answer">Code goes here:</label> --><br/>
	<input type="submit" value="Run" />
</form>

mysite/code_and_crossword/templates/code_and_crossword/crossword.html
<h1> You're on the crossword question in level {{ question.level }}.<br>
Question: {{ question.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!-- input form for uploading code -->
<form action="{% url 'code_and_crossword:crossword_check' question.level %}" method="post">
	{% csrf_token %}
    <input type="text" name="answer" id="submission {{ question.level }}" value="# Alphabets and digits only" />
     <!-- <label for="answer">Code goes here:</label> --><br/>
	<input type="submit" value="Run" />
</form>

mysite/code_and_crossword/templates/code_and_crossword/index.html
You're at the code-and-crossword index.

{% if code_questions %}
    <ul>
    <li>{{ code_count }} coding challenges are available</li>
    </ul>
{% endif %}

{% if crossword_questions %}
    <ul>
    <li>{{ crossword_count }} crossword puzzles are available</li>
    </ul>
{% endif %}

{% if not code_questions and not crossword_questions %}
    <p>No challenges are available.</p>
{% endif %}

Pick a timed challenge:
<form action="{% url 'code_and_crossword:code' 1 %}" method="post">
{% csrf_token %}
    <input type="radio" name="challenge_choice_1" id="30" value="first_radio" /><label for="challenge_choice_1">30 min</label><br />
    <input type="radio" name="challenge_choice_2" id="60" value="second_radio" /><label for="challenge_choice_2">60 min</label><br />
    <input type="radio" name="challenge_choice_3" id="90" value="third_radio" /><label for="challenge_choice_3">90 min</label><br />
<input type="submit" value="Enter Challenge" />
</form>

mysite/code_and_crossword/templates/code_and_crossword/leaderboard.html
<head>
<!-- Start Styles. Move the 'style' tags and everything between them to between the 'head' tags -->
<style type="text/css">
.myTable { width:480px;background-color:#eee;border-collapse:collapse; }
.myTable th { background-color:#000;color:white;width:50%; }
.myTable td { min-width: 90px;}
.myTable td, .myTable th { padding:5px;border:1px solid #000; }
</style>
<!-- End Styles -->
</head>
<body>
<h1>Global game results: </h1>

<table class="myTable">
<tr>
<th>Handle</th><th>Code Score</th><th>Crossword Score</th><th>Total Score</th>
</tr>
<tr>
<td>nautilus</td><td>10</td><td>10</td><td>20</td>
</tr>
<tr>
<td>oyster_perpetual</td><td>30</td><td>20</td><td>50</td>
</tr>
<tr>
<td>seamaster</td><td>20</td><td>10</td><td>30</td>
</tr>
</table>
</body>

mysite/code_and_crossword/templates/code_and_crossword/success.html
<h1> Successfully completed {{ success_type }} question: {{ question.question }} in level {{ question.level }} </h1>

<!-- Button for next question here -->